### ISSUE TITLE
Problem when installing GTStoWIS2

### ISSUE THREAD

**Issue by ren-ozk** [wmo-im/GTStoWIS2#46]
The following problem occurred when trying to install GTStoWIS2 on a Docker CentOS image.
This is because the default Centos image's locale is POSIX and the installation script contains characters other than ascii.

```
Obtaining file:///GTStoWIS2
    Complete output from command python setup.py egg_info:
    packages = ['GTStoWIS2']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/GTStoWIS2/setup.py", line 27, in <module>
        long_description=(read('README.rst')),
      File "/GTStoWIS2/setup.py", line 18, in read
        return codecs.open(os.path.join(here, *parts), 'r').read()
      File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 854: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /GTStoWIS2/
```

I think there are two solutions to this problem: 

1. specify encoding when python script open the file (if you need, I send PR)
2. add a description of locale to README

I would like to recommend No.1, because users may not be able to change the locale for some reason.

**Comment by petersilva** [comment]
This is a bit puzzling, I would accept a PR if you have time to provide one.

thoughts:

It is odd that POSIX does not use UTF-8.  UTF-8 is the default on linux for... um... a decade or more?  
( https://unix.stackexchange.com/questions/112216/which-terminal-encodings-are-default-on-linux-and-which-are-most-common ) lists 2007 as the transition date for Debian... 

The io is being done by some routine in the setup.py package, so not sure what sort of PR for 1 you could produce... hmm,... I googled and found this: https://vstinner.github.io/posix-locale.html which seems to indicate that python >= 3.7 should be OK without any modification. Perhaps you can check which python version is on your image?  

I would ordinarily suggest just setting your locale to something more reasonable... with a LANG setting, or use C, but I guess your point is that it is the default... hmm...

Option 3: remove the French characters from the README file... sad, but will not compromise readability.

Option 3 is probably the most practical thing to do... but I don't understand why centos has this problem.
more discussion welcome.

**Comment by ren-ozk** [comment]
Thank you for your comment !
First, let me describe the details of my environment.

```
docker : 20.10.6
baseimage : centos:7
Dockerfile : please see attach
python : 3.6.8
```
[Dockerfile.txt](https://github.com/wmo-im/GTStoWIS2/files/7043304/Dockerfile.txt)


On the docker image of centos:7 the filesystemnencoding of python3.6 seems to be ascii.
I think this is the cause of this issue.

```
>>> import sys
>>> sys.getfilesystemencoding()
'ascii'.
```

> I would ordinarily suggest just setting your locale to something more reasonable

I think you are right about this suggestion.
In fact, when I changed the locale to en_US.UTF-8 in the Docker container above, 
the installation finished without any problems.

> Perhaps you can check which python version is on your image?

I failed to install GTStoWIS2 with python 3.6.
I updated python to 3.8 and tried again, and the installation was successful !

---
Setting the locale or upgrading the python version is probably the right way to do.
However, as you can see the PR(#47), this change is very simple.
I think it's also good to include this change so that users don't have to worry about locale and python version.
